### ISSUE TITLE
Could you please provide details on the training process and parameters used?

### ISSUE THREAD

**Issue by zxy1234321** [McHz1s/RECIST_Co_training#1]
I was looking through your project on GitHub and I found it really interesting. I was wondering if you could provide some details on the training process and parameters that you used in your model? It would be great if you could include this information in your README file, as it would help me understand your project better and potentially replicate your work.

Thank you for your time and consideration!

**Comment by McHz1s** [comment]
Detail readme will can late.

Simply speaking, their is only one launcher, submit.py, and all training is started by python -u submit.py --config path_to_the_config_file, e.g., use "python -u submit.py configs/kits/recist_2d_segmentation/kits_swinTBase_dual.yaml", to train swin-T-Base. You need to transform your dataset to coco format with RECIST(key "recist_points") annotations.

**Comment by McHz1s** [comment]
Detail readme will can late.

Simply speaking, their is only one launcher, submit.py, and all training is started by python -u submit.py --config path_to_the_config_file, e.g., use "python -u submit.py --config configs/kits/recist_2d_segmentation/kits_swinTBase_dual.yaml", to train swin-T-Base. You need to transform your dataset to coco format with RECIST(key "recist_points") annotations.

**Comment by McHz1s** [comment]
Readme has been added

**Comment by zxy1234321** [comment]
您好 想请问下RECIST-induced Reliable Learning: Geometry-driven Label Propagation for Universal Lesion Segmentation的代码有没有开源
